#!/usr/bin/env bash
# Configure your domain zone so that the subdomain
# www points to your load-balancer IP.

output() {
	dig "$2.$1" | awk '/;; ANSWER SECTION/ {getline;
	printf "The subdomain %s is a %s record and points to %s\n", sdom, $4, $5}' sdom="$2"
}

if [[ $# -gt 1 ]];
then
	output "$1" "$2"
else
	output "$1" "www"
	output "$1" "lb-01"
	output "$1" "web-01"
	output "$1" "web-02"
fi
