#!/usr/bin/env bash
# Redirect to 301 Moved Permanently

sudo apt-get update
sudo apt-get install nginx -y
sudo echo "Hello World!" | sudo tee "/var/www/html/index.html"
sudo sed -i '24 i \\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4i permanent;' /etc/nginx/sites-enabled/default
sudo echo "Ceci n'est pas une page" | sudo tee "/usr/share/nginx/html/404.html"
sudo service nginx restart