#!/usr/bin/env bash
# Configure Nginx to listen on port 80

sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install nginx -y
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
