#!/usr/bin/env bash
# Configure Nginx to listen on port 80

sudo apt-get update
sudo apt-get upgrade -y
sudo sed -i '24 i listen 80 default_server' /etc/nginx/sites-enabled/default
sudo sed -i '24 i listen 80 default_server' /etc/nginx/sites-available/default
sudo service nginx restart
