#!/usr/bin/env bash
# Write a Bash script that displays the PID,
# along with the process name, of processes whose
# name contain the word bash
echo $$ bash | grep bash; echo $BASHPID bash | grep bash
