#!/usr/bin/env bash
# Print "Best School" 10 times, print bad luck for 4th iteration
# and print good luck for the 8th iteration
x=1
while [ $x -le 10 ]
do
	if [[ "$x" == 4 ]]
	then
		echo "bad luck"
	elif [[ "$x" == 8 ]]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	x=$(( x + 1 ))
done
