#!/usr/bin/env bash
# Print numbers from 1 to 20 with while loop and make conditions
# with their case statements
x=1
while [ $x -le 20 ]
do
	echo $x
	case $x in
	4)
	echo "bad luck from China"
	;;

	9)
	echo "bad luck from Japan"
	;;

	17)
	echo "bad luck from Italy"
	;;
	esac
	x=$(( x + 1 ))
done
