#!/usr/bin/env bash
# Prints the hours and minutes of the day
hour=0
minutes=1
while [ $hour -le 12 ]
do
	echo "Hour: "$hour
		while [ $minutes -le 59 ]
		do
			echo $minutes
			minutes=$(( minutes + 1 ))
		done
	minutes=1
	hour=$(( hour + 1 ))
done
