#!/usr/bin/env bash
# Configures the container to run nginx user as nginx while listening port 8080

sudo sed -i "0 i user nginx;" /etc/nginx/nginx.conf
sudo sed -i "24 i listen 8080;" /etc/nginx/sites-enable/default
sudo service nginx restart
