#!/usr/bin/env bash
# Configures the container to run nginx user as nginx while listening port 8080

sudo sed -i "s/#user www-data/user nginx/g" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-enable/default
sudo chmod 644 /etc/nginx/nginx.conf
sudo pkill apache2
sudo -u nginx
sudo service nginx restart
